baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "Andreia | Creative Design Agency"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Accueil"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "A propos"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Blog"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Système d’écoute"
    url     = "blog"
    weight  = 4
 

# Site Params
[params]
  logo = "images/Group.svg"
  logo_footer = "images/iconb.svg"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
 

  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/fondo.jpeg"
    heading               = "Bienvenue"
    primary_button        = "Lire les articles"
    primary_button_url    = "portfolio"
    secondary_button      = "Mon système de veille"
    secondary_button_url  = "blog"

  [params.portfolio]
    enable    = true
    title     = "DERNIERS RESUMES"
    view_project = "Lire le résumé"
    more_works = "MORE WORKS"
    scroll_down = "Voir les articles"


  